spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/odontosuite
    username: postgres
    password: odontosuite

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

storage:
  location: uploads/patients

server:
  port: 8081